### GET /
GET http://localhost:4001

### POST /auth/register
POST http://localhost:4001/auth/register
Content-Type: application/json

{
    "username":"test@gmail.com",
    "password":"12345678"
}

### POST /auth/lgoin
POST http://localhost:4001/auth/login
Content-Type: application/json

{
    "username":"test@gmail.com",
    "password":"12345678"
}

### GET STATS
GET http://localhost:4001/stats
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUwMTExMjM4LCJleHAiOjE3NTAxOTc2Mzh9.tozSXdqKx83YDWRENFHWMllkDlIZgBbSkzfQISqOwws



### update stats
PUT  http://localhost:4001/stats
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUwMTY3NTAwLCJleHAiOjE3NTAyNTM5MDB9.n743yIBuqVLRe9hNtHWsYtrxoFDunbPol3m05LAjN74

{
    "outcome":1
}



